"""Name not unique

Revision ID: c7f490da45c4
Revises: eefc6c7c30ed
Create Date: 2023-03-13 19:21:15.841056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f490da45c4'
down_revision = 'eefc6c7c30ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_table', sa.Column('task_no', sa.String(length=30), nullable=False))
    op.drop_constraint('association_table_task_id_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'task', ['task_no'], ['no'])
    op.drop_column('association_table', 'task_id')
    op.drop_constraint('task_name_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_name_key', 'task', ['name'])
    op.add_column('association_table', sa.Column('task_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_task_id_fkey', 'association_table', 'task', ['task_id'], ['no'])
    op.drop_column('association_table', 'task_no')
    # ### end Alembic commands ###
