"""Initial

Revision ID: eefc6c7c30ed
Revises: 
Create Date: 2023-03-12 13:46:34.090940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefc6c7c30ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('no', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('solved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('no'),
    sa.UniqueConstraint('name')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('association_table',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.no'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('theme_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('theme')
    op.drop_table('task')
    # ### end Alembic commands ###
